# Generated by Django 3.2 on 2022-01-13 12:46

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cart_checkout', '0002_auto_20220112_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
