# Generated by Django 3.2 on 2022-01-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='merch',
            name='has_sizes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
